ALTER TABLE "ShopSettings"
ADD COLUMN IF NOT EXISTS "garageLatitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "garageLongitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "attendanceRadiusMeters" INTEGER NOT NULL DEFAULT 20;

ALTER TABLE "Employee"
ADD COLUMN IF NOT EXISTS "facePhotoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "facePhotoUpdatedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "isAttendanceEligible" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "AttendancePayroll"
ADD COLUMN IF NOT EXISTS "checkInAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "checkOutAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "workedMinutes" INTEGER,
ADD COLUMN IF NOT EXISTS "attendanceMethod" TEXT DEFAULT 'manual',
ADD COLUMN IF NOT EXISTS "verificationProvider" TEXT,
ADD COLUMN IF NOT EXISTS "verificationStatus" TEXT DEFAULT 'not_configured',
ADD COLUMN IF NOT EXISTS "checkInVideoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "checkOutVideoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "checkInVerificationScore" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkOutVerificationScore" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkInLatitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkInLongitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkOutLatitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkOutLongitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkInDistanceMeters" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "checkOutDistanceMeters" DOUBLE PRECISION;

UPDATE "Employee"
SET "isAttendanceEligible" = false
WHERE COALESCE(LOWER("designation"), '') LIKE '%admin%';