-- AddColumn migration: Add Indian states and state codes

INSERT INTO "States" ("StateID", "StateName", "StateCode", "createdAt", "updatedAt") VALUES
('state-01', 'Jammu And Kashmir', '01', NOW(), NOW()),
('state-02', 'Himachal Pradesh', '02', NOW(), NOW()),
('state-03', 'Punjab', '03', NOW(), NOW()),
('state-04', 'Chandigarh', '04', NOW(), NOW()),
('state-05', 'Uttarakhand', '05', NOW(), NOW()),
('state-06', 'Haryana', '06', NOW(), NOW()),
('state-07', 'Delhi', '07', NOW(), NOW()),
('state-08', 'Rajasthan', '08', NOW(), NOW()),
('state-09', 'Uttar Pradesh', '09', NOW(), NOW()),
('state-10', 'Bihar', '10', NOW(), NOW()),
('state-11', 'Sikkim', '11', NOW(), NOW()),
('state-12', 'Arunachal Pradesh', '12', NOW(), NOW()),
('state-13', 'Nagaland', '13', NOW(), NOW()),
('state-14', 'Manipur', '14', NOW(), NOW()),
('state-15', 'Mizoram', '15', NOW(), NOW()),
('state-16', 'Tripura', '16', NOW(), NOW()),
('state-17', 'Meghalaya', '17', NOW(), NOW()),
('state-18', 'Assam', '18', NOW(), NOW()),
('state-19', 'West Bengal', '19', NOW(), NOW()),
('state-20', 'Jharkhand', '20', NOW(), NOW()),
('state-21', 'Orissa', '21', NOW(), NOW()),
('state-22', 'Chhattisgarh', '22', NOW(), NOW()),
('state-23', 'Madhya Pradesh', '23', NOW(), NOW()),
('state-24', 'Gujarat', '24', NOW(), NOW()),
('state-26', 'Dadra And Nagar Haveli & Daman And Diu', '26', NOW(), NOW()),
('state-27', 'Maharashtra', '27', NOW(), NOW()),
('state-29', 'Karnataka', '29', NOW(), NOW()),
('state-30', 'Goa', '30', NOW(), NOW()),
('state-31', 'Lakshadweep', '31', NOW(), NOW()),
('state-32', 'Kerala', '32', NOW(), NOW()),
('state-33', 'Tamil Nadu', '33', NOW(), NOW()),
('state-34', 'Puducherry', '34', NOW(), NOW()),
('state-35', 'Andaman And Nicobar', '35', NOW(), NOW()),
('state-36', 'Telangana', '36', NOW(), NOW()),
('state-37', 'Andhra Pradesh', '37', NOW(), NOW()),
('state-38', 'Ladakh', '38', NOW(), NOW()),
('state-97', 'Other Territory', '97', NOW(), NOW()),
('state-99', 'Other Country', '99', NOW(), NOW())
ON CONFLICT DO NOTHING;
